# Home page background image
background:
    - /images/bg/magnifier/2026年6月.jpg
    - /images/bg/magnifier/丽娜.jpg
    - /images/bg/magnifier/凯撒.jpg
    - /images/bg/magnifier/可琳.jpg
    - /images/bg/magnifier/妮可.jpg
    - /images/bg/magnifier/安东.jpg
    - /images/bg/magnifier/安比.jpg
    - /images/bg/magnifier/星见雅.jpg
    - /images/bg/magnifier/月城柳.jpg
    - /images/bg/magnifier/本.jpg
    - /images/bg/magnifier/朱鸢.jpg
    - /images/bg/magnifier/柏妮思.jpg
    - /images/bg/magnifier/格莉丝.jpg
    - /images/bg/magnifier/派派.jpg
    - /images/bg/magnifier/浅羽悠真.jpg
    - /images/bg/magnifier/猫又.jpg
    - /images/bg/magnifier/珂蕾妲.jpg
    - /images/bg/magnifier/简.jpg
    - /images/bg/magnifier/艾莲.jpg
    - /images/bg/magnifier/莱卡恩.jpg
    - /images/bg/magnifier/莱特.jpg
    - /images/bg/magnifier/赛斯.jpg
    - /images/bg/magnifier/露西.jpg
    - /images/bg/magnifier/青衣.jpg
    - /images/bg/archive/2.3剧情壁纸_1.jpg
    - /images/bg/archive/2.3剧情壁纸_10.jpg
    - /images/bg/archive/2.3剧情壁纸_2.jpg
    - /images/bg/archive/2.3剧情壁纸_3.jpg
    - /images/bg/archive/2.3剧情壁纸_4.jpg
    - /images/bg/archive/2.3剧情壁纸_5.jpg
    - /images/bg/archive/2.3剧情壁纸_6.jpg
    - /images/bg/archive/2.3剧情壁纸_7.jpg
    - /images/bg/archive/2.3剧情壁纸_8.jpg
    - /images/bg/archive/2.3剧情壁纸_9.jpg
    - /images/bg/archive/2.4剧情壁纸_1.jpg
    - /images/bg/archive/2.4剧情壁纸_10.jpg
    - /images/bg/archive/2.4剧情壁纸_11.jpg
    - /images/bg/archive/2.4剧情壁纸_12.jpg
    - /images/bg/archive/2.4剧情壁纸_13.jpg
    - /images/bg/archive/2.4剧情壁纸_14.jpg
    - /images/bg/archive/2.4剧情壁纸_15.jpg
    - /images/bg/archive/2.4剧情壁纸_16.jpg
    - /images/bg/archive/2.4剧情壁纸_2.jpg
    - /images/bg/archive/2.4剧情壁纸_3.jpg
    - /images/bg/archive/2.4剧情壁纸_4.jpg
    - /images/bg/archive/2.4剧情壁纸_5.jpg
    - /images/bg/archive/2.4剧情壁纸_6.jpg
    - /images/bg/archive/2.4剧情壁纸_7.jpg
    - /images/bg/archive/2.4剧情壁纸_8.jpg
    - /images/bg/archive/2.4剧情壁纸_9.jpg
    - /images/bg/archive/2.5剧情壁纸_1.jpg
    - /images/bg/archive/2.5剧情壁纸_10.jpg
    - /images/bg/archive/2.5剧情壁纸_11.jpg
    - /images/bg/archive/2.5剧情壁纸_12.jpg
    - /images/bg/archive/2.5剧情壁纸_13.jpg
    - /images/bg/archive/2.5剧情壁纸_14.jpg
    - /images/bg/archive/2.5剧情壁纸_15.jpg
    - /images/bg/archive/2.5剧情壁纸_16.jpg
    - /images/bg/archive/2.5剧情壁纸_17.jpg
    - /images/bg/archive/2.5剧情壁纸_18.jpg
    - /images/bg/archive/2.5剧情壁纸_2.jpg
    - /images/bg/archive/2.5剧情壁纸_3.jpg
    - /images/bg/archive/2.5剧情壁纸_4.jpg
    - /images/bg/archive/2.5剧情壁纸_5.jpg
    - /images/bg/archive/2.5剧情壁纸_6.jpg
    - /images/bg/archive/2.5剧情壁纸_7.jpg
    - /images/bg/archive/2.5剧情壁纸_8.jpg
    - /images/bg/archive/2.5剧情壁纸_9.jpg
    - /images/bg/archive/2.6剧情壁纸_1.jpg
    - /images/bg/archive/2.6剧情壁纸_10.jpg
    - /images/bg/archive/2.6剧情壁纸_11.jpg
    - /images/bg/archive/2.6剧情壁纸_12.jpg
    - /images/bg/archive/2.6剧情壁纸_13.jpg
    - /images/bg/archive/2.6剧情壁纸_14.jpg
    - /images/bg/archive/2.6剧情壁纸_2.jpg
    - /images/bg/archive/2.6剧情壁纸_3.jpg
    - /images/bg/archive/2.6剧情壁纸_4.jpg
    - /images/bg/archive/2.6剧情壁纸_5.jpg
    - /images/bg/archive/2.6剧情壁纸_6.jpg
    - /images/bg/archive/2.6剧情壁纸_7.jpg
    - /images/bg/archive/2.6剧情壁纸_8.jpg
    - /images/bg/archive/2.6剧情壁纸_9.jpg
    - /images/bg/archive/2.7剧情壁纸_1.jpg
    - /images/bg/archive/2026年6月.jpg
    - /images/bg/archive/影像档案_「妄想」特典.jpg
    - /images/bg/archive/影像档案_「福」至沓来.jpg
    - /images/bg/archive/影像档案_不要温和地走入那良夜.jpg
    - /images/bg/archive/影像档案_临界推演：千面终局.jpg
    - /images/bg/archive/影像档案_云霞同归处.jpg
    - /images/bg/archive/影像档案_仲夏游梦绮谭.jpg
    - /images/bg/archive/影像档案_兔子小姐百分百.jpg
    - /images/bg/archive/影像档案_出击！差评大作战.jpg
    - /images/bg/archive/影像档案_卧底蓝调.jpg
    - /images/bg/archive/影像档案_可曾记得梦.jpg
    - /images/bg/archive/影像档案_天使与缪斯妄想.jpg
    - /images/bg/archive/影像档案_失梦者奇谭.jpg
    - /images/bg/archive/影像档案_失踪邦口.jpg
    - /images/bg/archive/影像档案_奇花异旅.jpg
    - /images/bg/archive/影像档案_妄想协鸣于此刻.jpg
    - /images/bg/archive/影像档案_将临未抵的深渊1.jpg
    - /images/bg/archive/影像档案_将临未抵的深渊2.jpg
    - /images/bg/archive/影像档案_将眼泪与过往一同埋葬（上）.jpg
    - /images/bg/archive/影像档案_将眼泪与过往一同埋葬（下）.jpg
    - /images/bg/archive/影像档案_幸运当头.jpg
    - /images/bg/archive/影像档案_引力映叙时光.jpg
    - /images/bg/archive/影像档案_微光引灯时.jpg
    - /images/bg/archive/影像档案_心愿代投站.jpg
    - /images/bg/archive/影像档案_我是艾莲，在忙，有事留言.jpg
    - /images/bg/archive/影像档案_新·艾利都日落时 上.jpg
    - /images/bg/archive/影像档案_无人喝彩之冠.jpg
    - /images/bg/archive/影像档案_旧梦的安可曲.jpg
    - /images/bg/archive/影像档案_星流霆击.jpg
    - /images/bg/archive/影像档案_残梦未尽之时Ⅰ.jpg
    - /images/bg/archive/影像档案_残梦未尽之时Ⅱ.jpg
    - /images/bg/archive/影像档案_流光札记.jpg
    - /images/bg/archive/影像档案_滚烫寻鲜记.jpg
    - /images/bg/archive/影像档案_潜影暗流交锋.jpg
    - /images/bg/archive/影像档案_火狱骑行.jpg
    - /images/bg/archive/影像档案_灾潮特遣分队.jpg
    - /images/bg/archive/影像档案_白银的复苏.jpg
    - /images/bg/archive/影像档案_目不可及.jpg
    - /images/bg/archive/影像档案_空明寻剑录.jpg
    - /images/bg/archive/影像档案_老朋友，新委托！.jpg
    - /images/bg/archive/影像档案_虎啸有风生.jpg
    - /images/bg/archive/影像档案_虚拟杀机.jpg
    - /images/bg/archive/影像档案_虚狩加冕之时.jpg
    - /images/bg/archive/影像档案_解忧轶事录.jpg
    - /images/bg/archive/影像档案_轻羽逐风.jpg
    - /images/bg/archive/影像档案_连携调查：神之迷宫.jpg
    - /images/bg/archive/影像档案_迟吟的浪涌.jpg
    - /images/bg/archive/影像档案_闪耀的此刻.jpg
    - /images/bg/archive/影像档案_集结委托回归丽都2.5.jpg
    - /images/bg/archive/版本前瞻&活动_XBOX上线.jpg
    - /images/bg/archive/版本前瞻&活动_一周年纪念.jpg
    - /images/bg/archive/版本前瞻&活动_不要温和地走入那良夜.jpg
    - /images/bg/archive/版本前瞻&活动_云霞同归处.jpg
    - /images/bg/archive/版本前瞻&活动_可曾记得梦.jpg
    - /images/bg/archive/版本前瞻&活动_在被遗忘的废墟之上.jpg
    - /images/bg/archive/版本前瞻&活动_将临未抵的深渊.jpg
    - /images/bg/archive/版本前瞻&活动_将眼泪与过往一同埋葬.jpg
    - /images/bg/archive/版本前瞻&活动_微光引灯时.jpg
    - /images/bg/archive/版本前瞻&活动_新·艾利都日落时.jpg
    - /images/bg/archive/版本前瞻&活动_旧梦的安可曲.jpg
    - /images/bg/archive/版本前瞻&活动_星流霆击.jpg
    - /images/bg/archive/版本前瞻&活动_特别访客:悠真.jpg
    - /images/bg/archive/版本前瞻&活动_特别访客：照.jpg
    - /images/bg/archive/版本前瞻&活动_英雄不死于往昔.jpg
    - /images/bg/archive/版本前瞻&活动_虚拟杀机.jpg
    - /images/bg/archive/版本前瞻&活动_迟吟的浪涌.jpg
    - /images/bg/archive/版本前瞻&活动_闪耀的此刻.jpg

# Loading image
loading: /images/loading.gif

# Main menu navigation
menu:
    Home:
        name: house
        theme: solid
        link: /
    About:
        name: id-card
        theme: solid
        link: /about
    Archives:
        name: box-archive
        theme: solid
        link: /archives
    Categories:
        name: bookmark
        theme: solid
        link: /categories
    Tags:
        name: tags
        theme: solid
        link: /tags

# Side info card
card:
    enable: true
    description: |
        爱生活 & INFJ & IT工程师
    iconLinks:
        GitHub:
            name: github
            theme: brands
            link: https://github.com/AeonArjormon
        QQ:
            name: qq
            theme: brands
            link: https://wpa.qq.com/msgrd?v=3&uin=2960503784&site=qq&menu=yes&jumpflag=1
        WeChat:
            name: weixin
            theme: brands
            link: /images/wx.png
        Email:
            name: envelope
            theme: regular
            link: mailto:AeonArjormon@outlook.com
        TikTok:
            name: tiktok
            theme: brands
            link: https://v.douyin.com/SmgEcMg/
        Gitee:
            name: git
            theme: brands
            link: https://gitee.com/py4zcc
    friendLinks:
        赞赏: /images/zs.png

# Footer info
footer:
    since: 2024
    ICP:
        enable: false
        code:
        link:

# Polyfill
polyfill:
    enable: true
    features:
        - default

# Highlight.js
highlight:
    enable: true
    style: github

# KaTeX math rendering
math:
    enable: false

# Image preview
preview:
    enable: true
