# ParticleX Theme Configuration (Override)

# Avatar image
avatar: /images/cat.jpeg

# Home page background image
background:
    - https://img5.runjiapp.com/duoteimg/dtnew_newsup_img/202109/20210901112013_67031.jpeg
    - https://www.toopic.cn/public/uploads/small/1715139851115171513985117.jpg
    - https://www.toopic.cn/public/uploads/small/1658047060509165804706088.png
    - https://www.toopic.cn/public/uploads/small/1704264333943170426433387.jpg

# Loading image
loading: /images/loading.gif

# Main menu navigation
menu:
    Home:
        name: house
        theme: solid
        link: /
    About:
        name: id-card
        theme: solid
        link: /about
    Archives:
        name: box-archive
        theme: solid
        link: /archives
    Categories:
        name: bookmark
        theme: solid
        link: /categories
    Tags:
        name: tags
        theme: solid
        link: /tags

# Side info card
card:
    enable: true
    description: |
        爱生活 & INFJ & IT工程师
    iconLinks:
        GitHub:
            name: github
            theme: brands
            link: https://github.com/AeonArjormon
        QQ:
            name: qq
            theme: brands
            link: https://wpa.qq.com/msgrd?v=3&uin=2960503784&site=qq&menu=yes&jumpflag=1
        WeChat:
            name: weixin
            theme: brands
            link: /images/wx.png
        Email:
            name: envelope
            theme: regular
            link: mailto:AeonArjormon@outlook.com
        TikTok:
            name: tiktok
            theme: brands
            link: https://v.douyin.com/SmgEcMg/
        Gitee:
            name: git
            theme: brands
            link: https://gitee.com/py4zcc
    friendLinks:
        赞赏: /images/zs.png

# Footer info
footer:
    since: 2024
    ICP:
        enable: false
        code:
        link:

# Polyfill
polyfill:
    enable: true
    features:
        - default

# Highlight.js
highlight:
    enable: true
    style: github

# KaTeX math rendering
math:
    enable: false

# Image preview
preview:
    enable: true
